PROJ_DIR := $(realpath $(CURDIR)/..)
SOURCE_DIR := $(PROJ_DIR)
BUILD_DIR := $(PROJ_DIR)/Build

TARGET = YetAnotherChessGame.o

https://riptutorial.com/makefile/example/21376/building-from-different-source-folders-to-different-target-folders