name: C/C++ CI on Mac

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on:  	macos-lates

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -f MAKEFILE all target_file=YetAnotherChessGame
    - name: Download a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: YetAnotherChessGame
        path: YetAnotherChessGame
