name: C/C++ CI on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -f MAKEFILE all target_file=YetAnotherChessGame.exe
    - name: Download a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: YetAnotherChessGame.exe
        path: YetAnotherChessGame.exe
