name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -f MAKEFILE all target_file=YetAnotherChessGame.o
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: YetAnotherChessGame.o
        path: 
